apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-redis
  labels:
    app: expiration-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-redis
  template:
    metadata:
      labels:
        app: expiration-redis
    spec:
      containers:
      - name: expiration-redis
        image: redis:latest 
        ports:
        - containerPort: 6379

 
    