apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo
  labels:
    app: tickets-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
      - name: tickets-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
      
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
  labels:
    app: tickets-mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    name: db
    targetPort: 27017
  selector:
    app: tickets-mongo
    